[Finishes #187355083] Added the postgress and the sequilizer configur…
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #10
Opened 2024-04-09 17:32 UTC by Christian-Ishimwe

_### Description_

This pull request aims to use postgres as our SQL database as well as using Sequelizer as our ORM Tool

1. **Dependency Installation:**
 `npm install`

2. **File Structure:**
 Our sequilezer follows this directory:  

   ```
       src/database/
         |- models/   # Directory to store all your database models
         |- migrations/  # Directory to store migration files for database schema changes
         |- seeds/      # Directory to store seed data for testing or initial population
         |- config/ config.ts # File for Sequelize configuration and connection setup
        
     ```

3. **Configuration:**
   - Created a `.env` file in the project root directory to store sensitive database credentials securely.
   - follow .env.example  to create .env file

4. **Sequelize Initialization:**
   - Created `database.ts` to manage Sequelize configuration and connection.

5. **Model Example (Optional):**
   - Provided an example of defining a simple `Admin` model in `models/admins.ts` 

7. **Sequelizer-cli**
refer to package.json for using the Sequelizer-cli commands on bash, ex: f
or migrations.
```shell
npm run migrate
``` 
**Note**

-By using sequelizer-cli, you will get the .js files, hence you will need to change them manually to .ts file.
-In .sequelizerc file, we proveded the paths for sequelizer-cli, while in ` 'config': path.resolve('./src/database/config', 'config.js'),` we referenced in dist directorym which mean you will be required to run this script: /
**Testing**

```bash
npm run build
``` 
Please review and test this initial setup. Further development and testing are required for full integration into the API.

**Additional links**

1. Sequilezer cli Documentation: https://sequelize.org/docs/v6/other-topics/migrations/#configuration
2. SQL Commands:  https://www.w3schools.com/sql/default.asp

2024-04-10 13:34 UTC, UmuhireJessie commented on README.md
Readme files are for providing guideline on the whole project, not specifically to a particular features. Unless it is the main feature. You can provide us details about the chore by updating description section on pull request instead.

2024-04-10 13:36 UTC, UmuhireJessie commented on src/database/database.ts
> +const sequelize = new Sequelize(`${process.env.DATABASE_URL}`, {
Add necessary environment variables in `.env.example` file, e.g., NODE_ENV, DATABASE_URL, TEST_DATABASE_URL, PROD_DATABASE_URL and provide one sentence explaining each

2024-04-10 13:41 UTC, UmuhireJessie commented on src/models/userModels.ts
Please ensure that configure sequelize correctly, we should be having a structure like the following:
- src/database/config
- src/database/migrations
- src/database/models
- src/database/seeders

Also provide a sample code for each files, create a user seeder with an initial admin

2024-04-10 13:44 UTC, UmuhireJessie commented on package.json
update the script sections, with the scripts to run migrations, undo migration, seeders files undo seeds.
Check [here](https://sequelize.org/docs/v6/other-topics/migrations/)

2024-04-10 13:44 UTC, UmuhireJessie requested changes
Hello @Christian-Ishimwe, please check my comments

2024-04-12 07:44 UTC, UmuhireJessie commented on .env.example
Add NODE_ENV variable

2024-04-12 07:45 UTC, UmuhireJessie commented on .gitignore
> +src/database/migrations
You do not have to ignore migrations folder, this a crucial file while setting up a database

2024-04-12 07:46 UTC, UmuhireJessie commented on README.md
> +Description
Prefer providing us a descriptive Readme, if you want. Or else remove unnecessary details

2024-04-12 07:47 UTC, UmuhireJessie commented on package.json
Change scripts sections. [Here](https://sequelize.org/docs/v6/other-topics/migrations/) is a guide

2024-04-12 07:49 UTC, UmuhireJessie commented on src/database/config/config.ts
Remove this folder

2024-04-12 07:49 UTC, UmuhireJessie commented on src/config/config.json
Remove this folder

2024-04-12 07:55 UTC, UmuhireJessie commented on src/database/config/config.ts
Prefer using this instead:
```
const dotenv = require('dotenv')

dotenv.config()
module.exports = {
  development: {
    url: process.env.DATABASE_URL,
    dialect: 'postgres',
    logging: false
  },
  test: {
    url: process.env.TEST_DATABASE_URL,
    dialect: 'postgres',
    logging: false
  },
  production: {
    url: process.env.PROD_DATABASE_URL,
    dialect: 'postgres',
    logging: false
  }
}
```

And add an else if section in `src/database/models/index.ts`
```
let sequelize: any;
if (config.use_env_variable) {
  // @ts-ignore
  sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else if (config.url) {
  // @ts-ignore
  sequelize = new Sequelize(config.url, config)
} else {
  // @ts-ignore
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}
```

This way the code is clean and readable. Then in your `.env.example` you will have to use the following:
```
NODE_ENV=development
DATABASE_URL='Database url for development'
TEST_DATABASE_URL='Database url for test'
PROD_DATABASE_URL='Database url for production'
```

2024-04-12 07:56 UTC, UmuhireJessie commented on src/server.ts
> +const databaseUrl= process.env.DATABASE_URL
How are you having this `DATABASE_URL`, yet the your current configurations didn't have that environment?

2024-04-12 07:57 UTC, UmuhireJessie requested changes
Check my comments

2024-04-12 08:37 UTC, Christian-Ishimwe commented
i have corrected the requesed changes, please check out @UmuhireJessie

2024-04-12 08:48 UTC, UmuhireJessie commented on package-lock.json
Update scripts section

2024-04-12 08:51 UTC, UmuhireJessie requested changes
@Christian-Ishimwe check my comments. You can not label all the commit with `Finishes`, use that once you have completed everything and that you are ready.

2024-04-12 10:01 UTC, UmuhireJessie commented on .env.example
> -PORT='7000'
Add port.

2024-04-12 10:02 UTC, UmuhireJessie commented on package.json
> +    "undo-migrate": "sequelize db:migrate:undo:all"
add a script for undoing seed, and that of doing everything all at once for simplicity.

2024-04-12 10:10 UTC, UmuhireJessie requested changes
The migrations are not going through!
![image](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/86103578/ee7fbeb5-2593-47b3-a565-53e7c568371d)

Please do the following:
1. Ensure that you have tested everything before adding reviewers
2. Add a description with how can we test your chore manually, right now everyone is just imaging, what do we expect if the chore is successfully done, etc!
3. Squash the commits!

2024-04-14 10:58 UTC, UmuhireJessie commented on src/database/models/index.ts
> +const config = require(__dirname + '/../config/config.ts')[env];
change these lines with
```
const env = process.env.NODE_ENV || 'development';
const configSuffix = process.env.NODE_ENV === 'development' ? '.ts' : '.js';
const config = require(__dirname + `/../config/config${configSuffix}`)[env];
```

2024-04-14 11:18 UTC, UmuhireJessie commented on src/database/seeders/Admins.seeds.ts
This is not how we create seeders. Here is the [guide](https://sequelize.org/docs/v6/other-topics/migrations/#creating-the-first-seed)

2024-04-14 11:19 UTC, UmuhireJessie commented on src/database/models/admins.ts
The fields you have in you migration file and model file should be the same. If it is firstName, lastName, email and telephone, that is what should be in migration too

2024-04-14 11:20 UTC, UmuhireJessie requested changes
@Christian-Ishimwe please resolve the comments

2024-04-15 09:27 UTC, closed without merging