Ch integrate houndci
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #11
Opened 2024-04-10 20:10 UTC by lilika67

Why this important?

This is to automatically validate the codebase with standard style guides

Technically HoundCI has no official readme badge but there are services out there with which you can create a HoundCI badge.

2024-04-11 12:26 UTC, UmuhireJessie approved these changes

2024-04-11 12:29 UTC, UmuhireJessie requested changes
Great @lilika67, please squash the commits into one commit

2024-04-11 12:29 UTC, pacifiquemboni approved these changes

2024-04-12 10:39 UTC, UmuhireJessie approved these changes

2024-04-12 10:40 UTC, Celestin4 approved these changes

2024-04-12 10:52 UTC, merged