[Finishes #187373269] user registration
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #15
Opened 2024-04-15 11:01 UTC by lilika67

**What does this PR do?**
As a new user, they should  be able to create an account so that they can access the app's features and services.

Acceptance Criteria:

The sign-up form should include fields for the user's name, email, and password etc..

The email address should be validated to ensure it's a valid email format.

The password should be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.

After the user fills in the sign-up form and clicks "Submit," they should receive a confirmation message that their account has been created.

The user's account information (password) should be stored securely and hashed for security purposes.

**Description of Task to be completed?**

Acceptance Criteria:

The sign-up form should include fields for the user's name, email, and password etc..

The email address should be validated to ensure it's a valid email format.

The password should be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character.

After the user fills in the sign-up form and clicks "Submit," they should receive a confirmation message that their account has been created.

The user's account information (password) should be stored securely and hashed for security purposes.

**How should this be manually tested?**

1.   [Clone the  project](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn.git)
2. Navigate to branch by git checkout ft-userregistration-187373269
3. run **npm install** for installing the packages
4. run **npm run build**  to compile .ts files to .js file
5. run **npm run migrate** to create required table on your local database
6. run **npm run migrate:all** to update in case of any changes
7. run the project by **npm run dev**

**Screenshot**

**postman test**
![registration](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/125905987/f2d72d0d-7c62-49a0-816b-3d7077e8c7a5)

**registered users in database**
![reg2](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/125905987/c4f3cd7e-50c2-49fe-93da-19c8bda66d00)

**Relevant pivotal tracker stories?**
[pivotal tracker](https://www.pivotaltracker.com/story/show/187373269/comments/240839576)

2024-04-16 21:45 UTC, rwemakevin requested changes
consider my 2 comments, thanks.

2024-04-16 21:45 UTC, rwemakevin commented on src/controllers/userControllers.ts
> +export const registerUser = async (req: Request, res: Response): Promise<Response> => {
Since this user controller will be in charge of handling operations related with users, Can I suggest that we use a  class, that way we can have for instance a  class named "userController", which will encapsulate various methods related to user operations within our application?


![classAsAController](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/115710944/594f000b-fe11-4544-a0c0-6d725b59ea0a)

2024-04-16 21:45 UTC, rwemakevin commented on src/controllers/userControllers.ts
> +export const getUsers = async(req: Request, res: Response)=>{
Refer to my previous comment, same here. This can also be a method within the userController class. Thanks

2024-04-17 23:45 UTC, pacifiquemboni requested changes
1.This is good work sofar but i am not able to access your routes ie. ican't see app.use('/user', userRoute) so that i can use it to access all user's routes.

2.in user model i think it should be better if you differentiate route path ie. instead of having '/' on both get and post routes, you can use '/getUsers' on get route and '/register' on post route.

3.remember to add  NODE_ENV in your  .env.example file, because it is really needed on the part of database.

4.remember to add these 2 commands in your description; npm run build  to compile .ts file to .js files and npm run migrate  to  create  required table on your local database

2024-04-28 10:54 UTC, UmuhireJessie commented on src/tests/index.test.ts
Remove the file

2024-04-28 10:55 UTC, UmuhireJessie requested changes
Good work @lilika67, please do the following:
1. Remove files you are not using
2. Squash the commits into 1
3. Resolve the conflicts on your PR

2024-04-28 11:19 UTC, UmuhireJessie commented on src/controllers/userControllers.ts
> +            return res.status(500).json({ message: "Failed to register user" });
Test this line too

2024-04-28 11:19 UTC, UmuhireJessie commented on src/controllers/userControllers.ts
> +            return res.status(500).json({ message: "Failed to fetch users" });
Test this line

2024-04-30 11:06 UTC, igorihimbazwe approved these changes
Good work

2024-05-01 13:30 UTC, pacifiquemboni approved these changes

2024-05-07 14:57 UTC, UmuhireJessie commented on package.json
Apply changes on the script sections

2024-05-07 14:58 UTC, UmuhireJessie commented on src/controllers/userControllers.ts
> +      // const { password: userPassword,...userDetails } = newUser.dataValues;
Remove these comments. We should try as much as possible to write clean codes!

2024-05-07 14:58 UTC, UmuhireJessie commented on src/database/seeders/20240415080213-demo-user.ts
> +          password: 'Password123@',
Passwords should be hashed before being saved in the database

2024-05-07 14:58 UTC, UmuhireJessie commented on src/models/userModels.ts
Remove this file if you are not using it

2024-05-07 15:00 UTC, UmuhireJessie requested changes
Good work @lilika67, Please:
1. Work on the comments given
2. Ensure that all checks are passing

2024-05-08 10:20 UTC, UmuhireJessie approved these changes

2024-05-08 11:48 UTC, igorihimbazwe commented
good

2024-05-08 11:50 UTC, igorihimbazwe approved these changes
👍

2024-05-09 12:23 UTC, merged