[Delivers #187355094]A successfully registered user should receive an…
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #16
Opened 2024-04-15 13:02 UTC by venuste-20002

#### What does this PR do?
 A successfully registered user should receive an email to verify their account email
#### Description of Task to be completed?
by verifying you account you will provide you registering format role and you will receive the email said that you are successful register with the link to verify. 
#### How should this be manually tested?
after clone and install all the package 
- run using npm dev 
- using postman (localhost:7000/api/users/register)

#### What are the relevant pivotal tracker/Trello stories?
[pivotal tracker link ](https://www.pivotaltracker.com/story/show/187355094)

2024-04-21 16:52 UTC, lilika67 approved these changes

2024-05-07 11:17 UTC, UmuhireJessie commented on coverage/clover.xml
Remove coverage folder

2024-05-07 11:19 UTC, UmuhireJessie commented on src/database/seeders/20240415080213-demo-user.ts
> +          password: '',
Whatever password you give to the seed user should be hashed

2024-05-07 11:21 UTC, UmuhireJessie commented on src/routes/exampleRoutes.ts
Avoid committing unused/unimportant code. Remove them instead if you are not using them

2024-05-07 11:23 UTC, UmuhireJessie requested changes
Good work @venuste-20002, consider:
1. working on the comments given
2. Response is not correct when I send bad request, here is the screenshot. 
<img width="1500" alt="Screenshot 2024-05-07 at 13 31 20" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/86103578/2e99d901-6a3b-4651-918f-46d3d56bf7f2">

2024-05-09 18:55 UTC, Celestin4 approved these changes

2024-05-13 11:49 UTC, UmuhireJessie commented on coverage/clover.xml
Remove coverage folder

2024-05-13 11:51 UTC, UmuhireJessie commented on coverage/clover.xml
Remove coverage folder

2024-05-13 11:51 UTC, UmuhireJessie commented on coverage/clover.xml
Remove coverage folder

2024-05-13 22:49 UTC, igorihimbazwe approved these changes

2024-05-14 12:00 UTC, UmuhireJessie approved these changes

2024-05-14 12:01 UTC, merged