Finishes [#187355106] Ft profile page settings
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #21
Opened 2024-04-24 17:09 UTC by pacifiquemboni

1.What does this PR do?
Profile Page Settings

2.Description
Once user user is done with registration he/she will be able to see his/her profile(includes personal information and billing address) and he/she will be able to update it by adding additional information such as gender, birthdate etc.

3.Acceptance Criteria
I want to be able to Edit my profile, but i should NOT be able to edit another users profile
relevant pivotal tracker story https://www.pivotaltracker.com/story/show/187355106

4.steps followed to test this feature
i)clone develop branch git clone https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn.git
ii)Checkout to the branch using git checkout ft-profile-page-setting
iii)setup environment variables (.env file) following .env.example file
PORT="your port number"
DATABASE_URL="your_database_url"
NODE_ENV="your_database_level"(it shoulbe development, test or production)
iv)run npm run build to convert .ts files into .js format
v) run npm migrate:all to migrate provided models in you database
vi)run npm run dev to start the server

5.use :
npm run test to run tests and npx jest --coverage to see test coverage
http://localhost:your_port_number/docs to see swagger documenta

2024-04-26 16:29 UTC, lilika67 approved these changes

2024-04-26 18:12 UTC, Christian-Ishimwe approved these changes

2024-05-06 10:09 UTC, UmuhireJessie commented on .vscode/settings.json
Remove this folder

2024-05-06 10:10 UTC, UmuhireJessie commented on src/models/userModels.ts
Remove this file if you are not using it

2024-05-06 10:10 UTC, UmuhireJessie commented on src/tests/index.test.ts
Remove this file if you are not using it

2024-05-06 10:12 UTC, UmuhireJessie requested changes
Good job @pacifiquemboni, consider the following:
1. Work on the comments give
2. Resolve the conflicts and conversations

2024-05-09 16:42 UTC, lilika67 approved these changes

2024-05-20 17:59 UTC, UmuhireJessie approved these changes

2024-05-20 18:02 UTC, merged