[Finishes #187355045] Run codeclimate test coverage after passing the tests from circleci, then show Maintainablity Badge
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #25
Opened 2024-05-02 17:03 UTC by rwemakevin

### **What does this PR do?**
----------------------------
Integrates CircleCI with Codeclimate.

### **Description of Task to be completed**
---------------------------------------------------

After pushing the code, it undergoes testing in CircleCI. Once the tests pass, CircleCI forwards the test coverage data to Code Climate for comprehensive analysis, which includes evaluation of code quality, test coverage, and maintainability. Upon receiving the coverage data, Code Climate displays a maintainability badge on the README file

### How should this be manually tested?
----------------------------------------------
Simply clone the repo and , switch to this branch, install all the packages, then make changes, commit and push the code.

### What are the relevant pivotal tracker/Trello stories?
-----------------------------------------------------------------------
https://www.pivotaltracker.com/story/show/187355045

### Screenshots
-------------------------------------------------------------
![Mantainabilty Badge](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/115710944/4cffca21-c4b7-4858-a7e1-6095f14e4778)

2024-05-03 08:36 UTC, lilika67 approved these changes

2024-05-03 13:05 UTC, UmuhireJessie approved these changes

2024-05-03 13:24 UTC, shema-surge commented
Great work, Most checks pass

2024-05-03 13:25 UTC, shema-surge approved these changes
Most checks pass. great.

2024-05-03 13:39 UTC, shema-surge requested changes
The coverage directory should not be uploaded to github, It should be added to .gitignore

2024-05-07 11:07 UTC, UmuhireJessie approved these changes

2024-05-07 11:08 UTC, merged