#[Finishes 187355100] login feature
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #28
Opened 2024-05-05 16:11 UTC by Celse13

#### What does this PR do?

#### Description of Task to be completed?
This task is related to the implementation of the login functionality that will provide the user access to log in into our e-commerce platform
#### How should this be manually tested?
You can test the implementation of this functionality by running you server and after use "http://localhost:3000/docs/" with you defined port to access the swagger docs. From there, you can test the functionality on the swagger. 
#### Any background context you want to provide?
In order to login, you should have signed up and verify your account. 
#### What are the relevant pivotal tracker/Trello stories?
The pivotal tracker for this task is #187355086
#### Screenshots (if appropriate)
![Screenshot 2024-05-05 181128](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/117368635/cbbde286-6a2c-4df7-98d1-9a4234179706)

#### Questions:

2024-05-06 09:26 UTC, igorihimbazwe approved these changes

2024-05-06 10:02 UTC, UmuhireJessie commented on coverage/clover.xml
Remove coverage folder

2024-05-06 10:04 UTC, UmuhireJessie requested changes
Good Work @Celse13!
please work on the responses
<img width="1500" alt="Screenshot 2024-05-06 at 12 01 12" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/86103578/b9556ab2-4875-4c1f-92a3-6d44d876f1d3">

2024-05-09 19:59 UTC, Celestin4 approved these changes

2024-05-10 08:34 UTC, pacifiquemboni commented
good work brother👍, but work on conflicting files other wise you are on good truck

2024-05-11 18:20 UTC, UmuhireJessie approved these changes

2024-05-11 18:20 UTC, merged