[Delivers #187355126] The products should stop listing if the expiry
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #29
Opened 2024-05-05 20:51 UTC by Christian-Ishimwe

2024-05-28 13:29 UTC, Celestin4 commented on src/cronjobs/productsCron.ts
> +    html: `
Can you move this html template in src/helps/MailTemplate.ts as it is on develop
<img width="1106" alt="image" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/97307891/d86be9eb-1133-4fdf-adce-7b99cccc8531">

2024-05-28 13:53 UTC, Celestin4 commented on src/database/migrations/20240415075217-create-user.ts
wh for these changes

<img width="1072" alt="image" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/97307891/be8d172a-7066-439a-813d-6687f3798511">

2024-05-28 13:54 UTC, Celestin4 commented on src/cronjobs/productsCron.ts
It will be better when you adapt to nodemail that is currently defined in project

2024-05-28 13:55 UTC, Celestin4 requested changes
That's is my comment

2024-05-30 08:29 UTC, lilika67 approved these changes

2024-05-30 10:06 UTC, Celestin4 approved these changes

2024-05-30 13:15 UTC, UmuhireJessie commented on README.md
> +[![CircleCI](https://circleci.com/gh/atlp-rwanda/e-commerce-ones-and-zeroes-bn/tree/fc-product-expire.svg?style=svg)](https://app.circleci.com/pipelines/github/atlp-rwanda/e-commerce-ones-and-zeroes-
These should be set to the base branch, i.e., `develop` branch

2024-05-30 13:20 UTC, UmuhireJessie requested changes
Good work @Christian-Ishimwe, check my comment

2024-05-30 14:24 UTC, UmuhireJessie approved these changes

2024-05-30 14:25 UTC, merged