[Finishes #187355101] User Login By Google
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #36
Opened 2024-05-10 06:37 UTC by Christian-Ishimwe

## What does this PR do?
This PR allows User to Register and Sign in By Using Google

## Description of Task to be completed?
The Task was creating the feature which allows user to Register By using the Google api Aouth2, Passport JS and user will be able to login by using The google

## How should this be manually tested?

1.Install the required Packages
2.Set the node environments as .env.example
3. visit  https://console.cloud.google.com/ for creating the the project
4. for this for getting started and creating the credentials: https://www.passportjs.org/packages/passport-google-oauth20/

when you successful created credentials, use the browser to  visit : `http://127.0.0.1:8000/auth/` ,  then register
after that, you might need to  return to that page, when you click register again, you will receive the Token to be used: 

`{"message":"User signed in!","userToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWQxZjBkYS1lMGNiLTRlNDYtOTUyNy1jYjY2MThhZmRmN2MiLCJmaXJzdE5hbWUiOiJJU0hJTVdFIiwibGFzdE5hbWUiOiJDaHJpc3RpYW4iLCJyb2xlIjoidXNlciIsImlhdCI6MTcxMzMzNTY2MCwiZXhwIjoxNzEzOTQwNDYwfQ.0Tzq5QYq5ltEkKMosY23v_iysp6q1l5htskn4R54UUM"}`

copy that bearer Token, and use it in testing in Postman on this endpoint: 
`http://127.0.0.1:8000/users/profile`

## What are the relevant pivotal tracker/Trello stories?
My Story tracker: #187355101

**_### NOTE_**:
Make sure to use the callback within google console as: `http://127.0.0.1:8000/auth/google/callback`
Use the PORT of 8000

<img width="1154" alt="Screenshot 2024-04-26 at 08 18 51" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/88989844/d2dde4e8-b9c5-49a6-84cd-5f97e16166db">

2024-05-10 06:48 UTC, lilika67 approved these changes

2024-05-10 14:10 UTC, Celestin4 approved these changes

2024-05-10 14:17 UTC, pacifiquemboni approved these changes

2024-05-17 14:25 UTC, UmuhireJessie requested changes
Good work @Christian-Ishimwe, please squash the commits

2024-05-18 19:51 UTC, jniyonkuru approved these changes

2024-05-20 12:41 UTC, UmuhireJessie approved these changes

2024-05-20 12:41 UTC, merged