product availability
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #38
Opened 2024-05-16 11:17 UTC by lilika67

**What does this PR do?**
This PR is for the feature which will be allowing a seller to mark product in our store manually as available or un available for buyers to buy them

**Description of Task to be completed?** 

Products should be availed for buyers to purchase

As a seller, I should be able to mark a product as available or unavailable manually in order to make it available for the buyers or not.

Reasons can be: expiry date, low on stock, etc

**How should this be manually tested?**

Clone the project using git clone + url
step 1. Install the required Packages
step2. Execute **npm run build** to change typescript files to javascript files.
step3. Execute **npm run migrate:all** to run the migrations
step4. Execute **npm run dev** to start the server

**What are the relevant pivotal tracker**
[Pivotal tracker url]( https://www.pivotaltracker.com/story/show/187355110
)

**Screenshot**

![image](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/125905987/29cfa05d-ef23-4a05-ac88-601fee0d94f3)

2024-05-16 22:05 UTC, Celestin4 approved these changes

2024-05-28 14:02 UTC, Celestin4 commented on src/controllers/productStatusController.ts
> +          isAvailable: true,
suppose we was having 10 products , they it is both at one do we have to go and change this property manually. all you have to check availability using quantity property of product > o

2024-05-28 14:03 UTC, Celestin4 requested changes
Tha is my comments

2024-05-28 15:40 UTC, Celestin4 approved these changes

2024-05-30 19:56 UTC, igorihimbazwe approved these changes

2024-05-30 21:10 UTC, pacifiquemboni approved these changes

2024-05-31 10:02 UTC, UmuhireJessie approved these changes

2024-05-31 10:03 UTC, merged