Admin should be able to set users roles
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #39
Opened 2024-05-17 10:25 UTC by jniyonkuru

**What does this PR do?**
This PR is for the feature, which will be updating  a user role,  a privileged user can set role of a user

**Description of Task to be completed?**
An administrator user , should be able to change users' roles.
 by default a registered user will get a buyer role. an admin user will be able to change that role to any of the following(buyer,seller,admin)

**How should this be manually tested?**

Clone the project using git clone + url
step 1. Install the required Packages
step2. Execute npm run build to change typescript files to javascript files.
step3. Execute npm run migrate:all to run the migrations
step4. Execute npm run dev to start the server
step5. login  as an administrator
step4. Set user role [buyer,seller,admin

**screenShot**

![Screenshot from 2024-05-17 12-20-09](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/106654339/07d7ea5f-6fa5-45cc-82fc-80444d825ca8)
]

**What are the relevant pivotal tracker**
#187355108

2024-05-28 15:29 UTC, lilika67 approved these changes

2024-05-30 18:31 UTC, igorihimbazwe approved these changes

2024-05-30 18:42 UTC, pacifiquemboni approved these changes

2024-05-31 09:59 UTC, UmuhireJessie commented on README.md
> +[![CircleCI](https://circleci.com/gh/atlp-rwanda/e-commerce-ones-and-zeroes-bn/tree/develop.svg?style=svg)](https://app.circleci.com/pipelines/github/atlp-rwanda/e-commerce-ones-and-zeroes-bn/?branch
These should target the base branch `develop`

2024-05-31 10:01 UTC, UmuhireJessie requested changes
@jniyonkuru Check my comment and add a way to register a seller

2024-06-03 19:14 UTC, closed without merging