Fix [#187355106] profile settings
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #40
Opened 2024-05-21 08:08 UTC by pacifiquemboni

1.What does this PR do?
Profile Page Settings

2.Description
Once user user is done with registration he/she will be able to see his/her profile(includes personal information and billing address) and he/she will be able to update it by adding additional information such as gender, birthdate etc.

3.Acceptance Criteria
I want to be able to Edit my profile, but i should NOT be able to edit another users profile
relevant pivotal tracker story https://www.pivotaltracker.com/story/show/187355106

4.steps followed to test this feature
i)clone develop branch git clone https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn.git
ii)Checkout to the branch using git checkout ft-profile-page-setting
iii)setup environment variables (.env file) following .env.example file
PORT="your port number"
DATABASE_URL="your_database_url"
NODE_ENV="your_database_level"(it shoulbe development, test or production)
iv)run npm run build to convert .ts files into .js format
v) run npm migrate:all to migrate provided models in you database
vi)run npm run dev to start the server

5.use :
npm run test to run tests and npx jest --coverage to see test coverage
http://localhost:your_port_number/docs to see swagger documenta

2024-05-21 17:34 UTC, lilika67 approved these changes

2024-05-21 17:39 UTC, Celestin4 reviewed
These functionalities related to profile setting requiere user to be authenticated. I dont see where we need token to perform action.

2024-05-22 12:41 UTC, Celestin4 approved these changes

2024-05-24 17:38 UTC, UmuhireJessie requested changes
Check my comments and add screenshot of how profile setting feature works

2024-05-24 17:38 UTC, UmuhireJessie commented on src/routes/index.ts
> +router.use('/user', updateUserRoutes);
All routes of user entity should have the same prefix either `/user` or `/users`

2024-05-27 11:36 UTC, UmuhireJessie commented on src/docs/Users/updateUser.ts
> +  '/api/users/editUser/{id}': {
Avoid using words like 'editUser' or 'update-user' in routes

2024-05-27 11:39 UTC, UmuhireJessie commented on src/routes/updateUserRoutes.ts
> +  '/editUser/:id',
Same here!

2024-05-27 11:41 UTC, UmuhireJessie commented on src/docs/Users/updateUser.ts
Can we have one file for user routes?

2024-05-27 11:42 UTC, UmuhireJessie requested changes
Good job @pacifiquemboni, see my comments above

2024-05-27 16:27 UTC, lilika67 approved these changes

2024-05-27 17:26 UTC, UmuhireJessie approved these changes

2024-05-27 17:28 UTC, merged