[finishes #187355105] ft-update-user-password
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #44
Opened 2024-05-22 17:41 UTC by rwemakevin

### What does this PR do?
-----------------------------------------------------------------------------------------------------------------------------------------

This PR allows Signed in users to change their password

### Description of Task to be completed?
-----------------------------------------------------------------------------------------------------------------------------------------

The task is about changing user's password. Once a user has access to their account, i.e are logged in, they can update their password in case they want to.

### How should this be manually tested?
-----------------------------------------------------------------------------------------------------------------------------------------

1.Run `npm install` to install all packages

2.Set the node environments inside .env as shown in the table below

| variable | value |
|--------|--------|
| PORT | value |
| DATABASE_URL| value |
| NODE_ENV | value |
| JWT_SECRET| value | 

3.Run `npm run build` to transpile ts file

4.Finally run `npm run start` to start the development server

5.then test the functionality using swaggerUI or postman
   swaggerUI :localhost:PORT/docs
   endpoint to test: api/user/changepassword
   
  ### NOTE
  -----------------------------------------------------------------------------------------------------------------------------------------
  You need to log into your acount in order to update your password

2024-05-27 11:45 UTC, UmuhireJessie commented on src/tests/updateUserPassword.test.ts
> +// }));
Remove these!

2024-05-27 11:46 UTC, UmuhireJessie commented on src/tests/updateUserPassword.test.ts
> +    // expect(req.body.verifyNewPassword).toBe('newPassword');
Remove these comments

2024-05-27 11:46 UTC, UmuhireJessie commented on src/controllers/userControllers.ts
> +      console.log(getDecodedToken);
Remove this console

2024-05-27 11:47 UTC, UmuhireJessie requested changes
Good work @rwemakevin, please work on the comments above!

2024-06-01 13:43 UTC, rwemakevin commented on src/tests/updateUserPassword.test.ts
> +// }));
This is fixed now

2024-06-01 13:43 UTC, rwemakevin commented on src/tests/updateUserPassword.test.ts
> +    // expect(req.body.verifyNewPassword).toBe('newPassword');
This is fixed too

2024-06-01 22:28 UTC, UmuhireJessie approved these changes

2024-06-02 12:50 UTC, lilika67 approved these changes

2024-06-02 16:03 UTC, jniyonkuru approved these changes

2024-06-03 07:47 UTC, venuste-20002 approved these changes

2024-06-03 17:16 UTC, merged