Ft two factor authentication for seller 187355104
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #46
Opened 2024-05-25 12:12 UTC by venuste-20002

#### What does this PR do?
   
 The Two Factor Authentication for Sellers

#### Description of Task to be completed?

      This Task  Have the following Endpoint
  1. Endpoint: POST /toggle-2fa
   
          Description: This endpoint will allow a seller to enable or disable two-factor authentication.
            When a request is made to this endpoint, 
            the system will toggle the current state of 2FA for the specified user.

        Implementation Steps:
             .Fetch the user from the database using the provided userId.
             .If the user is not found, return a 404 Not Found response.
             .Toggle the use2FA field for the user.
             .Save the updated user information in the database.
             .Return a 200 OK response with a message indicating the new status of 2FA.

  2. Endpoint: POST /2fa-verify
          
      Description: This endpoint will verify the provided 2FA token for a seller. 
       If the token is valid, a JWT token is generated and returned.

      Implementation Steps:
         . Fetch the user from the database using the provided userId.
        . If the user is not found, return a 404 Not Found response.
        .Verify the provided 2FA token using the secret stored in the user's record.
        .If the token is valid, generate a JWT token and return it in the response.
        .If the token is invalid, return a 401 Unauthorized response with an appropriate message.

#### How should this be manually tested?

     after clone and install all the independences you used
     Swagger Documentation with the above end point to  test

#### What are the relevant pivotal tracker/Trello stories?

https://www.pivotaltracker.com/story/show/187355104

#### Screenshots (if appropriate)

![Screenshot 2024-05-22 174324](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/156195811/6a144f4d-6439-4f66-92ce-09678393098d)

2024-05-27 11:50 UTC, UmuhireJessie commented on README.md
> +[![CircleCI](https://circleci.com/gh/atlp-rwanda/e-commerce-ones-and-zeroes-bn/tree/develop.svg?style=svg)](https://app.circleci.com/pipelines/github/atlp-rwanda/e-commerce-ones-and-zeroes-bn/?branch
Please do not change these, we need to see the coverage and CI statuses on `develop` branch

2024-05-27 11:53 UTC, UmuhireJessie commented on src/controllers/sellerController.ts
Can you simplify the process based on what we agreed? Or, if you choose to continue with this, explain it in the Readme file and the description of the PR

2024-05-27 11:55 UTC, UmuhireJessie commented on src/database/seeders/20240415080213-demo-user.ts
> +          password: process.env.password,
A password should be hashed before being saved to the database, regardless of it being an environment variable

2024-05-27 11:57 UTC, UmuhireJessie requested changes
So far, so good @venuste-20002, please:
1. work on the comments
2. squash the commits
3. resolve the conflicts

2024-05-27 17:25 UTC, UmuhireJessie approved these changes

2024-05-31 10:49 UTC, UmuhireJessie commented on src/documents/1716834651217-WIN_20231125_19_36_42_Pro.jpg
What are these images for?

2024-05-31 10:51 UTC, UmuhireJessie requested changes
@venuste-20002 Check my comments

2024-05-31 17:25 UTC, UmuhireJessie requested changes
Good @venuste-20002, please resolve conflicts

2024-06-10 16:18 UTC, lilika67 approved these changes

2024-06-18 16:03 UTC, shema-surge approved these changes

2024-06-18 19:57 UTC, UmuhireJessie approved these changes

2024-06-18 19:57 UTC, merged