Eslint configuration
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #5
Opened 2024-04-05 14:06 UTC by Celse13

## What does this PR do?
Configure ESLint and Git Pre commit hook to run tests and ESlint format
## Description of Task to be completed?
This task was about to run Eslint, test, and format before the pre-commit
## How should this be manually tested?
You need to follow the common practice of pushing to the remote repositiory, by git add, git commit -m 'Add message' after that the Eslint will run lint and format to fix the indentation issue and make sure that the code follow ES6 guidelines
## Any background context you want to provide?
## What are the relevant pivotal tracker/Trello stories?
Configure ESLint and Git Pre commit hook to run tests and ESlint format
## Screenshots (if appropriate)
![Screenshot 2024-04-05 160144](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/117368635/640dc687-64e1-40fe-a13f-60f90d85c421)

## Questions

2024-04-06 12:21 UTC, UmuhireJessie requested changes
@Celse13 well done! Please do the following:
1. Squash the commits, 1 commit should be added to `develop`
2. Rebase to `develop`
3. Resolve the conflicts

2024-04-16 11:35 UTC, Christian-Ishimwe approved these changes

2024-04-25 18:14 UTC, UmuhireJessie approved these changes
Good!

2024-04-25 18:36 UTC, pacifiquemboni approved these changes

2024-04-25 18:42 UTC, merged