Ft users should be able to chat
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #53
Opened 2024-06-03 05:44 UTC by Celestin4

2024-06-03 17:54 UTC, shema-surge approved these changes

2024-06-03 18:53 UTC, UmuhireJessie commented on src/helps/chats.ts
Good!

2024-06-03 18:55 UTC, UmuhireJessie commented on src/routes/chatsRoutes.ts
> +// router.post('/', isAuthenticated, addChat);
Why are these commented?

2024-06-03 18:55 UTC, UmuhireJessie requested changes
@Celestin4 Check my comments

2024-06-03 19:02 UTC, UmuhireJessie approved these changes

2024-06-04 07:59 UTC, jniyonkuru approved these changes

2024-06-04 08:03 UTC, lilika67 approved these changes

2024-06-04 17:39 UTC, merged