[Finishes#187355108]Admin should be able to set roles/permissions
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #55
Opened 2024-06-04 07:52 UTC by jniyonkuru

2024-06-05 17:33 UTC, Celestin4 approved these changes

2024-06-06 10:42 UTC, igorihimbazwe approved these changes

2024-06-10 23:19 UTC, UmuhireJessie commented on README.md
> +https://e-commerce-ones-and-zeroes-bn-8.onrender.comt
This is not the actual link

2024-06-10 23:20 UTC, UmuhireJessie requested changes
Resolve the link in readme file

2024-06-14 16:57 UTC, UmuhireJessie approved these changes

2024-06-14 16:57 UTC, merged