[finishes #187355121] Feature for product searching
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #58
Opened 2024-06-10 20:08 UTC by lilika67

**What does this PR do??**
This PR is for the feature for searching for product on our website

**Description of Task to be completed?**
 A buyer needs to haver a way to search a product. by name, by price range, by category, etc it can also be a combination of two or more with AND operation.

**How should this be manually tested?** 

Step1> Clone The project
Step2> Switch to branch ft-productSearch
Step3> Install all packages by npm install
Step4> Run the project by npm run dev

**What are the relevant pivotal tracker**

https://www.pivotaltracker.com/story/show/187355121

2024-06-10 23:11 UTC, UmuhireJessie commented on src/routes/searchRoute.ts
> +// export default router;
Why are these commented?

2024-06-10 23:13 UTC, UmuhireJessie commented on src/routes/index.ts
> +// router.use('/search', searchRoutes);
why are you having this commented route? Remove it if you are not using it

2024-06-10 23:13 UTC, UmuhireJessie commented on src/docs/paths.ts
> +// import searchProductPath from './product/searchProduct';
Why are these commented?

2024-06-10 23:16 UTC, UmuhireJessie commented on src/docs/product/product.ts
> +          in: 'path',
It is better if this search keyword is a query parameter, just like others. Instead of making it an optional path parameter

2024-06-10 23:17 UTC, UmuhireJessie requested changes
See my comments

2024-06-11 19:56 UTC, Celestin4 approved these changes

2024-06-12 05:17 UTC, pacifiquemboni approved these changes

2024-06-13 17:32 UTC, shema-surge approved these changes

2024-06-13 17:33 UTC, venuste-20002 approved these changes

2024-06-13 17:43 UTC, UmuhireJessie approved these changes

2024-06-13 17:43 UTC, merged