[Fixes fx-user-login-and-registration-and-emails-theme]
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #61
Opened 2024-06-21 06:22 UTC by Celestin4

2024-06-27 20:33 UTC, UmuhireJessie commented
Can you resolve conflicts and rename your commit message? Consult https://www.pivotaltracker.com/help/articles/github_integration/

2024-07-02 06:54 UTC, UmuhireJessie commented on src/controllers/userControllers.ts
> +    console.log(data);
remove this console

2024-07-02 06:55 UTC, UmuhireJessie commented on src/helps/nodemailer.ts
> +    // console.error('Error sending email:', error);
On error, you may want to know what is happening

2024-07-02 06:57 UTC, UmuhireJessie requested changes
Check my comments and resolve conflicts

2024-07-02 12:39 UTC, UmuhireJessie approved these changes

2024-07-02 12:54 UTC, Celse13 approved these changes

2024-07-02 13:52 UTC, pacifiquemboni approved these changes

2024-07-02 13:56 UTC, shema-surge approved these changes

2024-07-02 15:04 UTC, merged