[bug fixes] Resetting Password
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #62
Opened 2024-06-22 11:00 UTC by Christian-Ishimwe

### Description
This PR is for modifying and adding validators for resetting password

- Modifying and styling of the email
- Adding password validators for  setting new password
- Modifying the error handler, for response

2024-07-03 10:58 UTC, Celestin4 approved these changes

2024-07-03 13:01 UTC, lilika67 approved these changes

2024-07-03 16:37 UTC, UmuhireJessie commented on src/controllers/userControllers.ts
> +    console.log(req.body);
remove this console

2024-07-03 16:38 UTC, UmuhireJessie requested changes
Check my comment

2024-07-05 07:31 UTC, UmuhireJessie approved these changes

2024-07-05 09:07 UTC, merged