[ Finishes #187355122 ] Buyer should be able to track their order status
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #63
Opened 2024-06-27 15:06 UTC by Celse13

1. What does this PR do?

It allows the buyer to track an order status

2. Description of task to be completed

The implementation is designed to allow the buyer to allow the tracking of the order from different stages, after being placed until it is delivered. The order status is handled in the notifications table and also in the push notifications

3. How should this be manually tested?

Clone the repository.
Checkout to the branch.
Install necessary dependencies.
Start the development server.
Utilize Swagger documentation to interact with the AP
register as a buyer, fill the address information, create an order from that you can retrieve that status of an order 

4. What are the relevant pivotal tracker
https://www.pivotaltracker.com/story/show/187355122

5. Screenshot
![Screenshot 2024-06-26 185408](https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/117368635/54d4f257-e371-4b26-828b-bcdb60bbc63a)

2024-06-27 19:45 UTC, Celestin4 approved these changes

2024-07-02 06:53 UTC, UmuhireJessie commented on .idea/codeStyles/Project.xml
Remove `.idea` folder and add it `.gitignore`

2024-07-02 06:54 UTC, UmuhireJessie requested changes
check the comments

2024-07-08 13:33 UTC, UmuhireJessie approved these changes

2024-07-11 15:29 UTC, Christian-Ishimwe approved these changes

2024-07-24 15:28 UTC, merged