Merge pull request #48 from atlp-rwanda/ft-seller-can-remove-item-fro…
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #65
Opened 2024-06-30 18:03 UTC by lilika67

**What does this PR do?**
This PR is the bug-fix for displaying all available products in our store as paginated.

**Description**
The products are displayed as ten products per page.

2024-07-02 06:50 UTC, UmuhireJessie commented on src/controllers/productController.ts
>            .json({ message: 'No available products in our store' });
If the product array is empty, it doesn't mean that it is an array. Consider returning an empty array

2024-07-02 06:51 UTC, UmuhireJessie requested changes
Good work @lilika67, please check my comment

2024-07-05 10:37 UTC, Celestin4 approved these changes

2024-07-05 10:37 UTC, UmuhireJessie approved these changes

2024-07-05 10:57 UTC, pacifiquemboni approved these changes

2024-07-05 11:01 UTC, shema-surge approved these changes

2024-07-05 18:02 UTC, merged