[Finishes #187940985] Product Recommendation
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #67
Opened 2024-07-11 14:41 UTC by Christian-Ishimwe

2024-07-11 19:46 UTC, venuste-20002 approved these changes

2024-07-12 09:00 UTC, Celse13 approved these changes

2024-07-12 09:51 UTC, Celestin4 approved these changes

2024-07-12 21:14 UTC, UmuhireJessie approved these changes

2024-07-12 21:18 UTC, UmuhireJessie requested changes
Check the cause of the frontend error; `401 error`
<img width="1512" alt="Screenshot 2024-07-12 at 23 06 10" src="https://github.com/user-attachments/assets/ac16ec77-bcb7-4093-85e4-f52ca51cae82">

2024-07-17 11:44 UTC, UmuhireJessie approved these changes

2024-07-17 11:44 UTC, merged