[Finishes #187355114]fixing get product for seller and updateProduct
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #70
Opened 2024-07-17 17:28 UTC by venuste-20002

1. What does this PR do?

Get all products for a single seller and fix the update product functionality.

2. Description of task to be completed

This is a bug fix for retrieving the products in all collections of the seller and improving the way the product is updated.

3. How should this be manually tested?

Clone the repository.
Checkout to the branch.
Install necessary dependencies.
Start the development server.
Utilize Swagger documentation to interact with the API.

2024-07-19 15:28 UTC, Celse13 approved these changes

2024-07-22 16:27 UTC, jniyonkuru approved these changes

2024-07-22 16:28 UTC, pacifiquemboni approved these changes

2024-07-22 18:00 UTC, UmuhireJessie commented on src/tests/register.test.ts
> -  //   (db.User.findOne as jest.Mock).mockResolvedValueOnce(null);
Remove this if there is no use

2024-07-22 18:01 UTC, UmuhireJessie requested changes
Please check my comments

2024-07-24 15:26 UTC, UmuhireJessie approved these changes

2024-07-24 18:05 UTC, merged