Ft updating password after x amount of time
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #73
Opened 2024-07-21 19:26 UTC by pacifiquemboni

## What Does This PR DO?
Users should be presented with an interface that prompts them to change their passwords every x amount of time  `and` Fix profile page settings

# ⚠️⚠️How to test this PR
1. Clone `develop` branch and checkout to `Ft-updating-password-after-x-amount-of-time`
2. Install all required dependencies `npm install`
3. Follow `.env.example` to create your `.env` file
use this `REACT_APP_PASSWORD_EXPIRATION_PERIOD_MINUTES` to add time you need to set your password to be expired, for testing purpose use 2 or 3 minutes.
5. Start the application using `npm start`
6.  Navigate to login and start by signing up, verify your account  and mmake sure sure you wait for 2 to 3 min so that your password can be expired then login
![Screenshot 2024-07-21 212540](https://github.com/user-attachments/assets/b4c09a6e-0402-4389-b656-df03e479ea32)

2024-07-21 20:06 UTC, lilika67 approved these changes

2024-07-21 21:30 UTC, Celestin4 approved these changes

2024-07-22 17:52 UTC, UmuhireJessie commented on src/middleware/changePasswordIgnored.ts
> +//         return res.redirect(`${process.env.CLIENT_URL}/reset/new-password?q=${token}`);
Can you remove these comments

2024-07-22 17:55 UTC, UmuhireJessie commented on src/helps/MailTemplate.ts
> +
Can you move the salutations in this container

2024-07-22 17:56 UTC, UmuhireJessie requested changes
@pacifiquemboni please check my comments

2024-07-24 08:57 UTC, Celse13 approved these changes

2024-07-24 15:26 UTC, UmuhireJessie approved these changes

2024-07-24 15:26 UTC, merged