[Finieshes #187355091] Setup API documentation using swagger
atlp-rwanda/e-commerce-ones-and-zeroes-bn pull request #9
Opened 2024-04-09 13:42 UTC by Celestin4

**1. What does this PR do?**

Setup API documentation using swagger

**2. Description of task to be completed**

The task involves establishing API documentation utilizing Swagger, a popular framework for documenting APIs. This process will streamline understanding and usage of the API by providing clear and structured documentation. Through Swagger, developers can easily explore endpoints, parameters, payloads, and response formats. It ensures consistency and clarity in communication between developers and consumers of the API. Implementing Swagger enhances the overall development process and promotes better collaboration within the development team.

Relevant pivotal tracker stories
https://www.pivotaltracker.com/story/show/187355091

**3. How should this be manually tested?**

- Try to access swagger UI by running the server and user this URL for swagger docs:
                         http://localhost:7000/docs/
-Try to write endpoints and make its documentation

**5. Screenshoots**
<img width="1435" alt="image" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/97307891/8e97e70a-fe10-4f97-9d72-98764086d1ad">

<img width="1440" alt="image" src="https://github.com/atlp-rwanda/e-commerce-ones-and-zeroes-bn/assets/97307891/60655710-f502-4813-8425-99bf0a960713">

2024-04-09 18:02 UTC, igorihimbazwe approved these changes
This is good work

2024-04-09 18:09 UTC, pacifiquemboni commented
this is good work but on my end api is not ending excution, it is continousily loading, double check and  let me know if it is on my end only

2024-04-10 08:13 UTC, pacifiquemboni approved these changes
cool👍

2024-04-10 11:29 UTC, UmuhireJessie commented on .DS_Store
Remove this file in stagged files

2024-04-10 11:29 UTC, UmuhireJessie commented on src/.DS_Store
Remove this file

2024-04-10 11:31 UTC, UmuhireJessie requested changes
Well done @Celestin4, please check my comments on specific files!

2024-04-11 08:42 UTC, lilika67 approved these changes

2024-04-12 10:34 UTC, UmuhireJessie approved these changes

2024-04-12 10:34 UTC, merged